apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/8dabac67-436b-4269-8462-3ce86054b8d0/resourcegroups/MC_ckode-nextcloud_nextcloud_eastus/providers/Microsoft.Compute/disks/next-az-disk
    volumeAttributes:
      fsType: ext4